name: Publish Docker

on:
    push:
        branches: [release]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@release
            - name: Publish to registry
              uses: elgohr/Publish-Docker-Github-Action@v5
              with:
                  registry: docker.pkg.github.com
                  name: docker.pkg.github.com/dtrokhlib/courses-api/kyouma337/courses.api
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  tags: 'develop'
